export const THEME_COOKIE = "knowledge-theme";
export const LANGUAGE_COOKIE = "knowledge-language";

export const DEFAULT_THEME = "light";
export const DEFAULT_LANGUAGE = "pt-BR";

export type ThemeMode = "light" | "dark";
export type Language = "pt-BR" | "en" | "es";

export const LANGUAGE_OPTIONS: Array<{ value: Language; label: string }> = [
  { value: "pt-BR", label: "Português" },
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
];

export function normalizeTheme(value?: string | null): ThemeMode {
  return value === "dark" ? "dark" : DEFAULT_THEME;
}

export function normalizeLanguage(value?: string | null): Language {
  if (value === "en" || value === "es") {
    return value;
  }

  return DEFAULT_LANGUAGE;
}

const dictionaries = {
  "pt-BR": {
    common: {
      open: "Abrir",
      course: "Curso",
      readAndAdvance: "Leia e avance",
      likes: "curtidas",
      comments: "comentarios",
      ratingSuffix: "de nota",
      averageRating: "de nota media",
      published: "Publicado",
      archived: "Arquivado",
      draft: "Rascunho",
      featured: "Destaque",
      featuredPrimary: "Destaque principal",
      views: "views",
      clicks: "cliques",
      reactionsRegistered: "reacoes registradas",
      averageOverall: "media geral",
      coursesAvailable: "cursos disponiveis",
      records: "registros",
      availableNow: "Disponivel agora",
      inDraft: "Em rascunho",
      prepare: "Em preparo",
      waitingRelease: "aguardando liberacao",
    },
    preferences: {
      themeLight: "Modo claro",
      themeDark: "Modo escuro",
      language: "Idioma",
    },
    auth: {
      headerTagline: "Plataforma de cursos em meteorologia por satélite",
      heroEyebrow: "Laboratório Virtual da OMM",
      heroTitle: "Cursos em meteorologia por satélites com leitura clara e acesso direto.",
      heroDescription: "Trilhas sobre dados de satélite, nowcasting, composições RGB e aplicações meteorológicas.",
      heroTopics: ["GOES-R", "Nowcasting", "Composições RGB", "Oceanografia"],
      heroFootnote: "Entre para acessar cursos, alertas e interacoes.",
      loginEyebrow: "Entrar",
      loginTitle: "Acesse sua conta",
      loginDescription: "Continue de onde parou.",
      forgotPasswordLink: "Esqueci minha senha",
      registerEyebrow: "Criar acesso",
      registerTitle: "Crie sua conta",
      registerDescription: "Cadastre seus dados para entrar na plataforma.",
      resetEyebrow: "Recuperar senha",
      resetTitle: "Recupere seu acesso",
      resetDescription: "Receba um codigo por e-mail e defina uma nova senha.",
      resetStepEmail: "E-mail de recuperacao",
      resetStepCode: "Codigo e nova senha",
      resetCodeLabel: "Codigo recebido",
      resetNewPasswordLabel: "Nova senha",
      resetSendCodeButton: "Enviar codigo",
      resetConfirmButton: "Alterar senha",
      resetBackToLogin: "Voltar",
      resetCodeSent: "Se o e-mail estiver cadastrado, enviaremos um codigo de recuperacao.",
      resetSuccess: "Senha alterada com sucesso. Entre usando a nova senha.",
      resetRequestError: "Nao foi possivel enviar o codigo.",
      resetConfirmError: "Nao foi possivel alterar a senha.",
      nameLabel: "Nome completo",
      emailLabel: "E-mail",
      passwordLabel: "Senha",
      confirmPasswordLabel: "Confirmar senha",
      signInButton: "Entrar",
      registerButton: "Criar conta e entrar",
      supportTitle: "Laboratório Virtual",
      supportDescription: "Acesse cursos, agenda, alertas e interações do VLab em um só lugar.",
      noAccount: "Ainda nao tem conta?",
      createAccount: "Criar cadastro",
      haveAccount: "Ja possui conta?",
      signInLink: "Fazer login",
      invalidCredentials: "Credenciais invalidas. Confira seu e-mail e senha.",
      registerError: "Nao foi possivel criar sua conta.",
      autoSignInError: "Conta criada, mas nao foi possivel autenticar automaticamente.",
    },
    layout: {
      platformTagline: "Plataforma de cursos em meteorologia por satélite.",
      navCourses: "Cursos",
      navAlerts: "Alertas",
      navPublications: "Publicacoes",
      navAnalytics: "Desempenho",
      notificationsAria: "Notificacoes",
      guestUser: "Usuario",
      adminRole: "Equipe editorial",
      readerRole: "Leitor",
      adminAccess: "Acesso administrativo ativo",
      authenticatedAccount: "Conta autenticada",
      signOut: "Sair",
    },
    dashboard: {
      heroEyebrow: "Laboratório Virtual da OMM",
      heroTitle: "Cursos em meteorologia por satélites.",
      heroDescription:
        "Missão do VLab: Apoiar a proteção da vida, do patrimônio e o desenvolvimento econômico por meio do aprimoramento dos serviços meteorológicos, climáticos, hidrológicos e de outras áreas ambientais correlatas, capacitando os Membros da OMM a utilizar dados de satélite em seus serviços e atividades científicas, por meio da coordenação e oferta de educação, treinamento e intercâmbio de conhecimentos em uma rede global de Centros de Excelência do VLab e Operadores de Satélites.",
      heroTopics: [
        "GOES-R",
        "Nowcasting",
        "Composições RGB",
        "Oceanografia",
        "Radiação",
        "Acesso, processamento e visualização",
        "Radares meteorológicos",
        "Webinars",
      ],
      newCourse: "Novo curso",
      spotlightNow: "Em destaque agora",
      readCoursePage: "Ler pagina do curso",
      inboxLabel: "Seu inbox",
      recentAlerts: "Alertas recentes",
      seeAllNotifications: "Ver todas as notificacoes",
      noAlertsTitle: "Seu inbox ainda esta vazio",
      noAlertsDescription: "Novos cursos publicados aparecem aqui.",
      liveNow: "No ar agora",
      publishedCourses: "Cursos publicados",
      noPublishedTitle: "Nenhum curso publicado ainda",
      noPublishedDescription:
        "Quando uma nova trilha entrar no ar, ela aparece aqui com resumo, capa e acesso direto ao Moodle.",
      youtubeEyebrow: "Canal YouTube do Centro de Excelência VLab no Brasil (INPE/CGCT/DISSM)",
      youtubeTitle: "Playlists temáticas para complementar seu aprendizado.",
      youtubeDescription:
        "Acompanhe as playlists do canal com aulas sobre os satélites GOES-R, Nowcasting, Oceanografia, Composições RGB, Radiação, Introdução ao Sensoriamento Remoto, Acesso, Processamento e Visualização de Dados de Satélites e Webinars da Comunidade.",
      youtubeOpenChannel: "Abrir canal",
      youtubeOpenPlaylist: "Abrir playlist",
      youtubePlaylists: "Playlists",
      youtubeRefresh: "Atualizar playlists",
      youtubeRefreshing: "Atualizando playlists",
      youtubeSynced: "Sincronizado as",
      youtubeFallback: "Exibindo conteudo de reserva enquanto o YouTube atualiza.",
      youtubeUpdateError: "Nao foi possivel atualizar as playlists agora.",
      youtubeEmptyTitle: "Nenhuma playlist encontrada agora",
      youtubeEmptyDescription: "O canal sera consultado novamente automaticamente.",
      youtubeVideo: "video",
      youtubeVideos: "videos",
    },
    notifications: {
      label: "Alertas",
      title: "Notificacoes",
      description: "Novos cursos publicados aparecem aqui.",
      unread: "Nao lidas",
      unreadDescription: "Itens ainda nao abertos.",
      emptyTitle: "Nenhuma notificacao por aqui",
      emptyDescription: "Novos cursos publicados aparecem aqui.",
      markAllRead: "Marcar todas como lidas",
      newLabel: "Nova",
      markRead: "Marcar como lida",
      markUnread: "Marcar como nao lida",
    },
    publications: {
      label: "Publicacoes",
      title: "Publicacoes e rascunhos",
      description: "Gerencie titulo, capa, destaque e status.",
      summary: "Resumo",
      publishAction: "Publicar",
      newLabel: "Nova publicacao",
      newTitle: "Novo curso",
      newDescription: "Preencha os dados principais, salve em rascunho e publique quando estiver pronto.",
      editDescription: "Ajuste o texto, as imagens e o destaque desta publicacao.",
    },
    analytics: {
      label: "Analises",
      title: "Desempenho dos cursos",
      description: "Visao geral dos cursos publicados.",
      viewsHelper: "Paginas de curso",
      clicksHelper: "Acessos ao Moodle",
      ctrHelper: "Conversao media",
      ratingHelper: "Avaliacoes",
      impactTab: "Impacto geral",
      conversionTab: "Saida para o Moodle",
      socialTab: "Resposta social",
      rankingTitle: "Ranking geral de impacto",
      scorePrefix: "Score",
      conversionTitle: "Leitura de saida para o Moodle",
      socialTitle: "Engajamento social e avaliativo",
      likesHelper: "Curtidas",
      commentsHelper: "Comentarios",
      averageHelper: "Media geral",
      ctrLabel: "CTR",
    },
    course: {
      curatorLabel: "Curadoria editorial",
      publishedIn: "Publicado em",
      courseDate: "Data do curso",
      communityAverage: "media da comunidade",
      aboutCourse: "Sobre o curso",
      recentReviews: "Avaliacoes recentes",
      reactTitle: "Reagir ao curso",
      interestSignal: "Sinal de interesse",
      accumulatedLikes: "curtidas acumuladas",
      liked: "Curtido",
      like: "Curtir",
      yourReading: "Sua leitura",
      reviewPlaceholder: "Compartilhe um comentario opcional sobre a experiencia com este curso.",
      saveReview: "Salvar avaliacao",
      publicComment: "Comentario publico",
      publicCommentDescription:
        "Use este espaco para registrar impressao de leitura, recomendacoes ou contexto adicional para quem ainda esta escolhendo a trilha.",
      commentPlaceholder: "Escreva seu comentario sobre o curso.",
      publishComment: "Publicar comentario",
      reviewSaved: "Avaliacao salva com sucesso.",
      commentPublished: "Comentario publicado.",
      likeError: "Nao foi possivel registrar o like.",
      reviewError: "Nao foi possivel salvar a avaliacao.",
      commentError: "Nao foi possivel publicar o comentario.",
      community: "Comunidade",
      readingsAndComments: "Leituras e comentarios",
      noComments: "Ainda nao ha comentarios publicados para este curso.",
      continueReading: "Continue lendo",
      moreCourses: "Mais cursos",
      noRelatedCourses: "Ainda nao existem cursos relacionados publicados.",
      continueInMoodle: "Continuar no Moodle",
      memberInteraction: "Interacao de membros",
      signInToInteractTitle: "Entre para reagir, avaliar e comentar.",
      signInToInteractDescription:
        "A leitura e os links ficam abertos para visitantes. Curtidas, avaliacoes e comentarios exigem login ou cadastro.",
    },
    courseForm: {
      createTitle: "Dados do curso",
      editTitle: "Editar publicacao",
      titleLabel: "Titulo",
      titlePlaceholder: "Curso de meteorologia espacial aplicada",
      summaryLabel: "Resumo",
      summaryPlaceholder: "Resumo curto para a pagina do curso.",
      descriptionLabel: "Descricao completa",
      descriptionPlaceholder: "Detalhe o contexto, publico, habilidades e motivacoes do curso.",
      urlLabel: "URL do Moodle",
      urlPlaceholder: "https://moodle.cptec.inpe.br/...",
      startsAtLabel: "Inicio do curso",
      endsAtLabel: "Termino do curso",
      scheduleHint: "Use a data real do curso; ela alimenta a pagina publica e o calendario.",
      imagesTitle: "Imagens e destaque",
      uploadLabel: "Upload local",
      uploadHint: "Envie capas e imagens de apoio.",
      externalUrlsLabel: "URLs externas",
      externalUrlsHint: "Use uma URL por linha.",
      featuredLabel: "Colocar este curso no destaque principal.",
      currentImages: "Imagens atuais",
      localFilesTitle: "Arquivos locais prontos",
      localFilesHint: "Os uploads locais ficam guardados neste navegador ate publicar ou limpar o rascunho.",
      removeFile: "Remover arquivo",
      draftHint: "Salve em rascunho e publique quando estiver pronto.",
      autosaveReady: "Rascunho local ativo",
      autosaveSaved: "O formulario continua salvo automaticamente neste navegador, inclusive apos sair da pagina.",
      autosaveRestored: "O conteudo montado antes foi recuperado neste navegador para voce continuar de onde parou.",
      lastSaved: "Ultimo autosave",
      clearLocalDraft: "Limpar rascunho local",
      saveDraft: "Salvar rascunho",
      saveChanges: "Salvar alteracoes",
    },
  },
  en: {
    common: {
      open: "Open",
      course: "Course",
      readAndAdvance: "Read and continue",
      likes: "likes",
      comments: "comments",
      ratingSuffix: "rating",
      averageRating: "average rating",
      published: "Published",
      archived: "Archived",
      draft: "Draft",
      featured: "Featured",
      featuredPrimary: "Featured highlight",
      views: "views",
      clicks: "clicks",
      reactionsRegistered: "reactions",
      averageOverall: "overall average",
      coursesAvailable: "courses available",
      records: "records",
      availableNow: "Available now",
      inDraft: "In draft",
      prepare: "In preparation",
      waitingRelease: "waiting to be published",
    },
    preferences: {
      themeLight: "Light mode",
      themeDark: "Dark mode",
      language: "Language",
    },
    auth: {
      headerTagline: "Satellite meteorology course platform",
      heroEyebrow: "WMO Virtual Laboratory",
      heroTitle: "Satellite meteorology courses with clear reading and direct access.",
      heroDescription: "Tracks on satellite data, nowcasting, RGB composites and meteorological applications.",
      heroTopics: ["GOES-R", "Nowcasting", "RGB composites", "Oceanography"],
      heroFootnote: "Sign in to access courses, alerts and interactions.",
      loginEyebrow: "Sign in",
      loginTitle: "Access your account",
      loginDescription: "Continue where you left off.",
      forgotPasswordLink: "Forgot password",
      registerEyebrow: "Create access",
      registerTitle: "Create your account",
      registerDescription: "Register your details to enter the platform.",
      resetEyebrow: "Password recovery",
      resetTitle: "Recover your access",
      resetDescription: "Receive a code by email and set a new password.",
      resetStepEmail: "Recovery email",
      resetStepCode: "Code and new password",
      resetCodeLabel: "Received code",
      resetNewPasswordLabel: "New password",
      resetSendCodeButton: "Send code",
      resetConfirmButton: "Change password",
      resetBackToLogin: "Back",
      resetCodeSent: "If the email is registered, we will send a recovery code.",
      resetSuccess: "Password changed successfully. Sign in with your new password.",
      resetRequestError: "Could not send the code.",
      resetConfirmError: "Could not change the password.",
      nameLabel: "Full name",
      emailLabel: "Email",
      passwordLabel: "Password",
      confirmPasswordLabel: "Confirm password",
      signInButton: "Sign in",
      registerButton: "Create account and enter",
      supportTitle: "Virtual Laboratory",
      supportDescription: "Access VLab courses, agenda, alerts and interactions in one place.",
      noAccount: "Don`t have an account yet?",
      createAccount: "Create account",
      haveAccount: "Already have an account?",
      signInLink: "Sign in",
      invalidCredentials: "Invalid credentials. Check your email and password.",
      registerError: "Could not create your account.",
      autoSignInError: "Account created, but automatic sign-in failed.",
    },
    layout: {
      platformTagline: "Satellite meteorology course platform.",
      navCourses: "Courses",
      navAlerts: "Alerts",
      navPublications: "Publications",
      navAnalytics: "Analytics",
      notificationsAria: "Notifications",
      guestUser: "User",
      adminRole: "Editorial team",
      readerRole: "Reader",
      adminAccess: "Administrative access enabled",
      authenticatedAccount: "Authenticated account",
      signOut: "Sign out",
    },
    dashboard: {
      heroEyebrow: "WMO Virtual Laboratory",
      heroTitle: "Satellite meteorology courses.",
      heroDescription:
        "VLab mission: support the protection of life and property and economic development by improving meteorological, climate, hydrological and related environmental services, enabling WMO Members to use satellite data in services and scientific activities through education, training and knowledge exchange across a global network of VLab Centres of Excellence and Satellite Operators.",
      heroTopics: [
        "GOES-R",
        "Nowcasting",
        "RGB composites",
        "Oceanography",
        "Radiation",
        "Access, processing and visualization",
        "Weather radars",
        "Webinars",
      ],
      newCourse: "New course",
      spotlightNow: "Featured now",
      readCoursePage: "Open course page",
      inboxLabel: "Your inbox",
      recentAlerts: "Recent alerts",
      seeAllNotifications: "See all notifications",
      noAlertsTitle: "Your inbox is still empty",
      noAlertsDescription: "New published courses appear here.",
      liveNow: "Live now",
      publishedCourses: "Published courses",
      noPublishedTitle: "No published courses yet",
      noPublishedDescription:
        "When a new learning path goes live, it will appear here with cover, summary and direct Moodle access.",
      youtubeEyebrow: "YouTube channel of the VLab Centre of Excellence in Brazil (INPE/CGCT/DISSM)",
      youtubeTitle: "Thematic playlists to complement your learning.",
      youtubeDescription:
        "Follow playlists with lessons on GOES-R satellites, Nowcasting, Oceanography, RGB Composites, Radiation, Introduction to Remote Sensing, Access, Processing and Visualization of Satellite Data, and Community Webinars.",
      youtubeOpenChannel: "Open channel",
      youtubeOpenPlaylist: "Open playlist",
      youtubePlaylists: "Playlists",
      youtubeRefresh: "Refresh playlists",
      youtubeRefreshing: "Refreshing playlists",
      youtubeSynced: "Synced at",
      youtubeFallback: "Showing fallback content while YouTube updates.",
      youtubeUpdateError: "Could not refresh playlists right now.",
      youtubeEmptyTitle: "No playlists found right now",
      youtubeEmptyDescription: "The channel will be checked again automatically.",
      youtubeVideo: "video",
      youtubeVideos: "videos",
    },
    notifications: {
      label: "Alerts",
      title: "Notifications",
      description: "New published courses appear here.",
      unread: "Unread",
      unreadDescription: "Items not opened yet.",
      emptyTitle: "No notifications here",
      emptyDescription: "New published courses appear here.",
      markAllRead: "Mark all as read",
      newLabel: "New",
      markRead: "Mark as read",
      markUnread: "Mark as unread",
    },
    publications: {
      label: "Publications",
      title: "Publications and drafts",
      description: "Manage title, cover, highlight and status.",
      summary: "Summary",
      publishAction: "Publish",
      newLabel: "New publication",
      newTitle: "New course",
      newDescription: "Fill in the main details, save as draft and publish when ready.",
      editDescription: "Adjust the text, images and highlight for this publication.",
    },
    analytics: {
      label: "Analytics",
      title: "Course performance",
      description: "Overview of published courses.",
      viewsHelper: "Course pages",
      clicksHelper: "Moodle visits",
      ctrHelper: "Average conversion",
      ratingHelper: "Ratings",
      impactTab: "Overall impact",
      conversionTab: "Moodle traffic",
      socialTab: "Social response",
      rankingTitle: "Overall impact ranking",
      scorePrefix: "Score",
      conversionTitle: "Moodle outbound traffic",
      socialTitle: "Social and rating engagement",
      likesHelper: "Likes",
      commentsHelper: "Comments",
      averageHelper: "Overall average",
      ctrLabel: "CTR",
    },
    course: {
      curatorLabel: "Editorial curation",
      publishedIn: "Published on",
      courseDate: "Course date",
      communityAverage: "community average",
      aboutCourse: "About the course",
      recentReviews: "Recent reviews",
      reactTitle: "React to this course",
      interestSignal: "Interest signal",
      accumulatedLikes: "total likes",
      liked: "Liked",
      like: "Like",
      yourReading: "Your reading",
      reviewPlaceholder: "Share an optional comment about your experience with this course.",
      saveReview: "Save review",
      publicComment: "Public comment",
      publicCommentDescription:
        "Use this space to leave reading impressions, recommendations or extra context for anyone still choosing a learning path.",
      commentPlaceholder: "Write your comment about the course.",
      publishComment: "Publish comment",
      reviewSaved: "Review saved successfully.",
      commentPublished: "Comment published.",
      likeError: "Could not register the like.",
      reviewError: "Could not save the review.",
      commentError: "Could not publish the comment.",
      community: "Community",
      readingsAndComments: "Readings and comments",
      noComments: "There are no published comments for this course yet.",
      continueReading: "Keep reading",
      moreCourses: "More courses",
      noRelatedCourses: "There are no related published courses yet.",
      continueInMoodle: "Continue in Moodle",
      memberInteraction: "Member interaction",
      signInToInteractTitle: "Sign in to react, rate and comment.",
      signInToInteractDescription:
        "Reading and links stay open to visitors. Likes, reviews and comments require sign-in or registration.",
    },
    courseForm: {
      createTitle: "Course details",
      editTitle: "Edit publication",
      titleLabel: "Title",
      titlePlaceholder: "Applied space meteorology course",
      summaryLabel: "Summary",
      summaryPlaceholder: "Short summary for the course page.",
      descriptionLabel: "Full description",
      descriptionPlaceholder: "Describe context, audience, skills and motivations for the course.",
      urlLabel: "Moodle URL",
      urlPlaceholder: "https://moodle.cptec.inpe.br/...",
      startsAtLabel: "Course start",
      endsAtLabel: "Course end",
      scheduleHint: "Use the real course date; it feeds the public page and calendar.",
      imagesTitle: "Images and highlight",
      uploadLabel: "Local upload",
      uploadHint: "Upload cover and supporting images.",
      externalUrlsLabel: "External URLs",
      externalUrlsHint: "Use one URL per line.",
      featuredLabel: "Place this course in the main highlight.",
      currentImages: "Current images",
      localFilesTitle: "Local files ready",
      localFilesHint: "Local uploads stay saved in this browser until you publish or clear the draft.",
      removeFile: "Remove file",
      draftHint: "Save as draft and publish when ready.",
      autosaveReady: "Local draft active",
      autosaveSaved: "This form keeps saving automatically in this browser, even if you leave the page.",
      autosaveRestored: "Your earlier draft was restored in this browser so you can continue where you stopped.",
      lastSaved: "Last autosave",
      clearLocalDraft: "Clear local draft",
      saveDraft: "Save draft",
      saveChanges: "Save changes",
    },
  },
  es: {
    common: {
      open: "Abrir",
      course: "Curso",
      readAndAdvance: "Leer y continuar",
      likes: "me gusta",
      comments: "comentarios",
      ratingSuffix: "de nota",
      averageRating: "de nota media",
      published: "Publicado",
      archived: "Archivado",
      draft: "Borrador",
      featured: "Destacado",
      featuredPrimary: "Destacado principal",
      views: "vistas",
      clicks: "clics",
      reactionsRegistered: "reacciones",
      averageOverall: "promedio general",
      coursesAvailable: "cursos disponibles",
      records: "registros",
      availableNow: "Disponible ahora",
      inDraft: "En borrador",
      prepare: "En preparación",
      waitingRelease: "pendiente de publicación",
    },
    preferences: {
      themeLight: "Modo claro",
      themeDark: "Modo oscuro",
      language: "Idioma",
    },
    auth: {
      headerTagline: "Plataforma de cursos en meteorología por satélite",
      heroEyebrow: "Laboratorio Virtual de la OMM",
      heroTitle: "Cursos de meteorología por satélite con lectura clara y acceso directo.",
      heroDescription: "Rutas sobre datos satelitales, nowcasting, composiciones RGB y aplicaciones meteorológicas.",
      heroTopics: ["GOES-R", "Nowcasting", "Composiciones RGB", "Oceanografía"],
      heroFootnote: "Entra para acceder a cursos, alertas e interacciones.",
      loginEyebrow: "Entrar",
      loginTitle: "Accede a tu cuenta",
      loginDescription: "Continua desde donde lo dejaste.",
      forgotPasswordLink: "Olvide mi contrasena",
      registerEyebrow: "Crear acceso",
      registerTitle: "Crea tu cuenta",
      registerDescription: "Registra tus datos para entrar en la plataforma.",
      resetEyebrow: "Recuperar contrasena",
      resetTitle: "Recupera tu acceso",
      resetDescription: "Recibe un codigo por correo y define una nueva contrasena.",
      resetStepEmail: "Correo de recuperacion",
      resetStepCode: "Codigo y nueva contrasena",
      resetCodeLabel: "Codigo recibido",
      resetNewPasswordLabel: "Nueva contrasena",
      resetSendCodeButton: "Enviar codigo",
      resetConfirmButton: "Cambiar contrasena",
      resetBackToLogin: "Volver",
      resetCodeSent: "Si el correo esta registrado, enviaremos un codigo de recuperacion.",
      resetSuccess: "Contrasena alterada con exito. Entra usando la nueva contrasena.",
      resetRequestError: "No fue posible enviar el codigo.",
      resetConfirmError: "No fue posible cambiar la contrasena.",
      nameLabel: "Nombre completo",
      emailLabel: "Correo",
      passwordLabel: "Contrasena",
      confirmPasswordLabel: "Confirmar contrasena",
      signInButton: "Entrar",
      registerButton: "Crear cuenta y entrar",
      supportTitle: "Laboratorio Virtual",
      supportDescription: "Accede a cursos, agenda, alertas e interacciones del VLab en un solo lugar.",
      noAccount: "Todavia no tienes cuenta?",
      createAccount: "Crear cuenta",
      haveAccount: "Ya tienes cuenta?",
      signInLink: "Iniciar sesion",
      invalidCredentials: "Credenciales invalidas. Revisa tu correo y contrasena.",
      registerError: "No fue posible crear tu cuenta.",
      autoSignInError: "La cuenta fue creada, pero no se pudo iniciar sesion automaticamente.",
    },
    layout: {
      platformTagline: "Plataforma de cursos en meteorología por satélite.",
      navCourses: "Cursos",
      navAlerts: "Alertas",
      navPublications: "Publicaciones",
      navAnalytics: "Analítica",
      notificationsAria: "Notificaciones",
      guestUser: "Usuario",
      adminRole: "Equipo editorial",
      readerRole: "Lector",
      adminAccess: "Acceso administrativo activo",
      authenticatedAccount: "Cuenta autenticada",
      signOut: "Salir",
    },
    dashboard: {
      heroEyebrow: "Laboratorio Virtual de la OMM",
      heroTitle: "Cursos de meteorología por satélite.",
      heroDescription:
        "Misión del VLab: apoyar la protección de la vida, el patrimonio y el desarrollo económico mediante la mejora de los servicios meteorológicos, climáticos, hidrológicos y de otras áreas ambientales relacionadas, capacitando a los Miembros de la OMM para utilizar datos satelitales en sus servicios y actividades científicas mediante educación, formación e intercambio de conocimientos en una red global de Centros de Excelencia del VLab y Operadores de Satélites.",
      heroTopics: [
        "GOES-R",
        "Nowcasting",
        "Composiciones RGB",
        "Oceanografía",
        "Radiación",
        "Acceso, procesamiento y visualización",
        "Radares meteorológicos",
        "Webinars",
      ],
      newCourse: "Nuevo curso",
      spotlightNow: "Destacado ahora",
      readCoursePage: "Abrir página del curso",
      inboxLabel: "Tu bandeja",
      recentAlerts: "Alertas recientes",
      seeAllNotifications: "Ver todas las notificaciones",
      noAlertsTitle: "Tu bandeja todavía está vacía",
      noAlertsDescription: "Los nuevos cursos publicados aparecen aquí.",
      liveNow: "En el aire",
      publishedCourses: "Cursos publicados",
      noPublishedTitle: "Aún no hay cursos publicados",
      noPublishedDescription:
        "Cuando una nueva ruta salga al aire, aparecerá aquí con portada, resumen y acceso directo a Moodle.",
      youtubeEyebrow: "Canal YouTube del Centro de Excelencia VLab en Brasil (INPE/CGCT/DISSM)",
      youtubeTitle: "Playlists temáticas para complementar tu aprendizaje.",
      youtubeDescription:
        "Acompaña playlists del canal con clases sobre satélites GOES-R, Nowcasting, Oceanografía, Composiciones RGB, Radiación, Introducción a la Teledetección, Acceso, Procesamiento y Visualización de Datos Satelitales y Webinars de la Comunidad.",
      youtubeOpenChannel: "Abrir canal",
      youtubeOpenPlaylist: "Abrir playlist",
      youtubePlaylists: "Playlists",
      youtubeRefresh: "Actualizar playlists",
      youtubeRefreshing: "Actualizando playlists",
      youtubeSynced: "Sincronizado a las",
      youtubeFallback: "Mostrando contenido de reserva mientras YouTube actualiza.",
      youtubeUpdateError: "No fue posible actualizar las playlists ahora.",
      youtubeEmptyTitle: "No se encontraron playlists ahora",
      youtubeEmptyDescription: "El canal sera consultado de nuevo automaticamente.",
      youtubeVideo: "video",
      youtubeVideos: "videos",
    },
    notifications: {
      label: "Alertas",
      title: "Notificaciones",
      description: "Los nuevos cursos publicados aparecen aquí.",
      unread: "No leídas",
      unreadDescription: "Elementos aún no abiertos.",
      emptyTitle: "No hay notificaciones aquí",
      emptyDescription: "Los nuevos cursos publicados aparecen aquí.",
      markAllRead: "Marcar todas como leídas",
      newLabel: "Nueva",
      markRead: "Marcar como leída",
      markUnread: "Marcar como no leída",
    },
    publications: {
      label: "Publicaciones",
      title: "Publicaciones y borradores",
      description: "Gestiona título, portada, destaque y estado.",
      summary: "Resumen",
      publishAction: "Publicar",
      newLabel: "Nueva publicación",
      newTitle: "Nuevo curso",
      newDescription: "Completa los datos principales, guarda como borrador y publica cuando esté listo.",
      editDescription: "Ajusta el texto, las imágenes y el destaque de esta publicación.",
    },
    analytics: {
      label: "Analítica",
      title: "Desempeño de los cursos",
      description: "Vista general de los cursos publicados.",
      viewsHelper: "Páginas del curso",
      clicksHelper: "Accesos a Moodle",
      ctrHelper: "Conversión media",
      ratingHelper: "Evaluaciones",
      impactTab: "Impacto general",
      conversionTab: "Salida a Moodle",
      socialTab: "Respuesta social",
      rankingTitle: "Ranking general de impacto",
      scorePrefix: "Puntuación",
      conversionTitle: "Tráfico de salida hacia Moodle",
      socialTitle: "Participación social y valoraciones",
      likesHelper: "Me gusta",
      commentsHelper: "Comentarios",
      averageHelper: "Promedio general",
      ctrLabel: "CTR",
    },
    course: {
      curatorLabel: "Curaduría editorial",
      publishedIn: "Publicado el",
      courseDate: "Fecha del curso",
      communityAverage: "promedio de la comunidad",
      aboutCourse: "Sobre el curso",
      recentReviews: "Evaluaciones recientes",
      reactTitle: "Reaccionar al curso",
      interestSignal: "Señal de interés",
      accumulatedLikes: "me gusta acumulados",
      liked: "Te gusta",
      like: "Me gusta",
      yourReading: "Tu lectura",
      reviewPlaceholder: "Comparte un comentario opcional sobre tu experiencia con este curso.",
      saveReview: "Guardar evaluación",
      publicComment: "Comentario público",
      publicCommentDescription:
        "Usa este espacio para registrar impresiones de lectura, recomendaciones o contexto adicional para quien aún está eligiendo la ruta.",
      commentPlaceholder: "Escribe tu comentario sobre el curso.",
      publishComment: "Publicar comentario",
      reviewSaved: "Evaluación guardada con éxito.",
      commentPublished: "Comentario publicado.",
      likeError: "No fue posible registrar el me gusta.",
      reviewError: "No fue posible guardar la evaluación.",
      commentError: "No fue posible publicar el comentario.",
      community: "Comunidad",
      readingsAndComments: "Lecturas y comentarios",
      noComments: "Todavía no hay comentarios publicados para este curso.",
      continueReading: "Seguir leyendo",
      moreCourses: "Más cursos",
      noRelatedCourses: "Todavía no existen cursos relacionados publicados.",
      continueInMoodle: "Continuar en Moodle",
      memberInteraction: "Interaccion de miembros",
      signInToInteractTitle: "Inicia sesion para reaccionar, valorar y comentar.",
      signInToInteractDescription:
        "La lectura y los enlaces quedan abiertos para visitantes. Me gusta, valoraciones y comentarios requieren login o registro.",
    },
    courseForm: {
      createTitle: "Datos del curso",
      editTitle: "Editar publicación",
      titleLabel: "Título",
      titlePlaceholder: "Curso de meteorología espacial aplicada",
      summaryLabel: "Resumen",
      summaryPlaceholder: "Resumen corto para la página del curso.",
      descriptionLabel: "Descripción completa",
      descriptionPlaceholder: "Describe el contexto, público, habilidades y motivaciones del curso.",
      urlLabel: "URL de Moodle",
      urlPlaceholder: "https://moodle.cptec.inpe.br/...",
      startsAtLabel: "Inicio del curso",
      endsAtLabel: "Fin del curso",
      scheduleHint: "Usa la fecha real del curso; alimenta la pagina publica y el calendario.",
      imagesTitle: "Imágenes y destaque",
      uploadLabel: "Carga local",
      uploadHint: "Sube portadas e imágenes de apoyo.",
      externalUrlsLabel: "URLs externas",
      externalUrlsHint: "Usa una URL por línea.",
      featuredLabel: "Colocar este curso en el destaque principal.",
      currentImages: "Imágenes actuales",
      draftHint: "Guarda como borrador y publica cuando esté listo.",
      saveDraft: "Guardar borrador",
      saveChanges: "Guardar cambios",
    },
  },
} as const;

export type Messages = (typeof dictionaries)[Language];

export function getMessages(language: Language): Messages {
  return dictionaries[language] ?? dictionaries[DEFAULT_LANGUAGE];
}
