export const THEME_COOKIE = "knowledge-theme";
export const LANGUAGE_COOKIE = "knowledge-language";

export const DEFAULT_THEME = "light";
export const DEFAULT_LANGUAGE = "pt-BR";

export type ThemeMode = "light" | "dark";
export type Language = "pt-BR" | "en" | "es";

export const LANGUAGE_OPTIONS: Array<{ value: Language; label: string }> = [
  { value: "pt-BR", label: "Português" },
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
];

export function normalizeTheme(value?: string | null): ThemeMode {
  return value === "dark" ? "dark" : DEFAULT_THEME;
}

export function normalizeLanguage(value?: string | null): Language {
  if (value === "en" || value === "es") {
    return value;
  }

  return DEFAULT_LANGUAGE;
}

const dictionaries = {
  "pt-BR": {
    common: {
      open: "Abrir",
      course: "Curso",
      readAndAdvance: "Leia e avance",
      likes: "curtidas",
      comments: "comentarios",
      ratingSuffix: "de nota",
      averageRating: "de nota media",
      published: "Publicado",
      archived: "Arquivado",
      draft: "Rascunho",
      featured: "Destaque",
      featuredPrimary: "Destaque principal",
      views: "views",
      clicks: "cliques",
      reactionsRegistered: "reacoes registradas",
      averageOverall: "media geral",
      coursesAvailable: "cursos disponiveis",
      records: "registros",
      availableNow: "Disponivel agora",
      inDraft: "Em rascunho",
      prepare: "Em preparo",
      waitingRelease: "aguardando liberacao",
    },
    preferences: {
      themeLight: "Modo claro",
      themeDark: "Modo escuro",
      language: "Idioma",
      enableEmailAlerts: "Ativar avisos por e-mail",
      disableEmailAlerts: "Desativar avisos por e-mail",
    },
    auth: {
      headerTagline: "Plataforma de cursos em ciencias espaciais",
      heroEyebrow: "knowledge",
      heroTitle: "Cursos em ciencias espaciais com leitura clara e acesso direto.",
      heroDescription: "Trilhas sobre satelites, clima, observacao da Terra e tempo espacial.",
      heroTopics: ["Satelites", "Clima", "Tempo espacial", "Observacao da Terra"],
      heroFootnote: "Entre para acessar cursos, alertas e interacoes.",
      loginEyebrow: "Entrar",
      loginTitle: "Acesse sua conta",
      loginDescription: "Continue de onde parou.",
      forgotPasswordLink: "Esqueci minha senha",
      registerEyebrow: "Criar acesso",
      registerTitle: "Crie sua conta",
      registerDescription: "Cadastre seus dados para entrar na plataforma.",
      resetEyebrow: "Recuperar senha",
      resetTitle: "Recupere seu acesso",
      resetDescription: "Receba um codigo por e-mail e defina uma nova senha.",
      resetStepEmail: "E-mail de recuperacao",
      resetStepCode: "Codigo e nova senha",
      resetCodeLabel: "Codigo recebido",
      resetNewPasswordLabel: "Nova senha",
      resetSendCodeButton: "Enviar codigo",
      resetConfirmButton: "Alterar senha",
      resetBackToLogin: "Voltar",
      resetCodeSent: "Se o e-mail estiver cadastrado, enviaremos um codigo de recuperacao.",
      resetSuccess: "Senha alterada com sucesso. Entre usando a nova senha.",
      resetRequestError: "Nao foi possivel enviar o codigo.",
      resetConfirmError: "Nao foi possivel alterar a senha.",
      nameLabel: "Nome completo",
      emailLabel: "E-mail",
      passwordLabel: "Senha",
      confirmPasswordLabel: "Confirmar senha",
      signInButton: "Entrar",
      registerButton: "Criar conta e entrar",
      altAccessLabel: "acesso alternativo",
      googleSignIn: "Entrar com Google",
      googleUnavailable: "Google indisponivel neste ambiente",
      supportTitle: "knowledge",
      supportDescription: "Acesse seus cursos, alertas e interacoes em um so lugar.",
      notificationOptIn: "Quero receber aviso por e-mail quando novos cursos forem publicados.",
      noAccount: "Ainda nao tem conta?",
      createAccount: "Criar cadastro",
      haveAccount: "Ja possui conta?",
      signInLink: "Fazer login",
      invalidCredentials: "Credenciais invalidas. Confira seu e-mail e senha.",
      registerError: "Nao foi possivel criar sua conta.",
      autoSignInError: "Conta criada, mas nao foi possivel autenticar automaticamente.",
    },
    layout: {
      platformTagline: "Plataforma de cursos em ciencias espaciais.",
      navCourses: "Cursos",
      navAlerts: "Alertas",
      navPublications: "Publicacoes",
      navAnalytics: "Desempenho",
      notificationsAria: "Notificacoes",
      guestUser: "Usuario",
      adminRole: "Equipe editorial",
      readerRole: "Leitor",
      adminAccess: "Acesso administrativo ativo",
      authenticatedAccount: "Conta autenticada",
      emailsEnabled: "Recebendo avisos de novos cursos",
      emailsDisabled: "Avisos por e-mail desativados",
      signOut: "Sair",
    },
    dashboard: {
      heroTitle: "Cursos em ciencias espaciais.",
      heroDescription: "Explore publicacoes sobre atmosfera, satelites, clima e tempo espacial.",
      newCourse: "Novo curso",
      spotlightNow: "Em destaque agora",
      readCoursePage: "Ler pagina do curso",
      inboxLabel: "Seu inbox",
      recentAlerts: "Alertas recentes",
      seeAllNotifications: "Ver todas as notificacoes",
      noAlertsTitle: "Seu inbox ainda esta vazio",
      noAlertsDescription: "Novos cursos publicados aparecem aqui.",
      liveNow: "No ar agora",
      publishedCourses: "Cursos publicados",
      noPublishedTitle: "Nenhum curso publicado ainda",
      noPublishedDescription:
        "Quando uma nova trilha entrar no ar, ela aparece aqui com resumo, capa e acesso direto ao Moodle.",
      onlyFeaturedTitle: "O destaque acima concentra as publicacoes ativas no momento",
      onlyFeaturedDescription: "Publique outros cursos para ampliar a selecao.",
    },
    notifications: {
      label: "Alertas",
      title: "Notificacoes",
      description: "Novos cursos publicados aparecem aqui.",
      unread: "Nao lidas",
      unreadDescription: "Itens ainda nao abertos.",
      emptyTitle: "Nenhuma notificacao por aqui",
      emptyDescription: "Novos cursos publicados aparecem aqui.",
      markAllRead: "Marcar todas como lidas",
      newLabel: "Nova",
      markRead: "Marcar como lida",
      markUnread: "Marcar como nao lida",
    },
    publications: {
      label: "Publicacoes",
      title: "Publicacoes e rascunhos",
      description: "Gerencie titulo, capa, destaque e status.",
      summary: "Resumo",
      publishAction: "Publicar",
      newLabel: "Nova publicacao",
      newTitle: "Novo curso",
      newDescription: "Preencha os dados principais, salve em rascunho e publique quando estiver pronto.",
      editDescription: "Ajuste o texto, as imagens e o destaque desta publicacao.",
    },
    analytics: {
      label: "Analises",
      title: "Desempenho dos cursos",
      description: "Visao geral dos cursos publicados.",
      viewsHelper: "Paginas de curso",
      clicksHelper: "Acessos ao Moodle",
      ctrHelper: "Conversao media",
      ratingHelper: "Avaliacoes",
      impactTab: "Impacto geral",
      conversionTab: "Saida para o Moodle",
      socialTab: "Resposta social",
      rankingTitle: "Ranking geral de impacto",
      scorePrefix: "Score",
      conversionTitle: "Leitura de saida para o Moodle",
      socialTitle: "Engajamento social e avaliativo",
      likesHelper: "Curtidas",
      commentsHelper: "Comentarios",
      averageHelper: "Media geral",
      ctrLabel: "CTR",
    },
    course: {
      curatorLabel: "Curadoria editorial",
      publishedIn: "Publicado em",
      communityAverage: "media da comunidade",
      aboutCourse: "Sobre o curso",
      recentReviews: "Avaliacoes recentes",
      reactTitle: "Reagir ao curso",
      interestSignal: "Sinal de interesse",
      accumulatedLikes: "curtidas acumuladas",
      liked: "Curtido",
      like: "Curtir",
      yourReading: "Sua leitura",
      reviewPlaceholder: "Compartilhe um comentario opcional sobre a experiencia com este curso.",
      saveReview: "Salvar avaliacao",
      publicComment: "Comentario publico",
      publicCommentDescription:
        "Use este espaco para registrar impressao de leitura, recomendacoes ou contexto adicional para quem ainda esta escolhendo a trilha.",
      commentPlaceholder: "Escreva seu comentario sobre o curso.",
      publishComment: "Publicar comentario",
      reviewSaved: "Avaliacao salva com sucesso.",
      commentPublished: "Comentario publicado.",
      likeError: "Nao foi possivel registrar o like.",
      reviewError: "Nao foi possivel salvar a avaliacao.",
      commentError: "Nao foi possivel publicar o comentario.",
      community: "Comunidade",
      readingsAndComments: "Leituras e comentarios",
      noComments: "Ainda nao ha comentarios publicados para este curso.",
      continueReading: "Continue lendo",
      moreCourses: "Mais cursos",
      noRelatedCourses: "Ainda nao existem cursos relacionados publicados.",
      continueInMoodle: "Continuar no Moodle",
    },
    courseForm: {
      createTitle: "Dados do curso",
      editTitle: "Editar publicacao",
      titleLabel: "Titulo",
      titlePlaceholder: "Curso de meteorologia espacial aplicada",
      summaryLabel: "Resumo",
      summaryPlaceholder: "Resumo curto para a pagina do curso.",
      descriptionLabel: "Descricao completa",
      descriptionPlaceholder: "Detalhe o contexto, publico, habilidades e motivacoes do curso.",
      urlLabel: "URL do Moodle",
      urlPlaceholder: "https://moodle.cptec.inpe.br/...",
      imagesTitle: "Imagens e destaque",
      uploadLabel: "Upload local",
      uploadHint: "Envie capas e imagens de apoio.",
      externalUrlsLabel: "URLs externas",
      externalUrlsHint: "Use uma URL por linha.",
      featuredLabel: "Colocar este curso no destaque principal.",
      currentImages: "Imagens atuais",
      localFilesTitle: "Arquivos locais prontos",
      localFilesHint: "Os uploads locais ficam guardados neste navegador ate publicar ou limpar o rascunho.",
      removeFile: "Remover arquivo",
      draftHint: "Salve em rascunho e publique quando estiver pronto.",
      autosaveReady: "Rascunho local ativo",
      autosaveSaved: "O formulario continua salvo automaticamente neste navegador, inclusive apos sair da pagina.",
      autosaveRestored: "O conteudo montado antes foi recuperado neste navegador para voce continuar de onde parou.",
      lastSaved: "Ultimo autosave",
      clearLocalDraft: "Limpar rascunho local",
      saveDraft: "Salvar rascunho",
      saveChanges: "Salvar alteracoes",
    },
  },
  en: {
    common: {
      open: "Open",
      course: "Course",
      readAndAdvance: "Read and continue",
      likes: "likes",
      comments: "comments",
      ratingSuffix: "rating",
      averageRating: "average rating",
      published: "Published",
      archived: "Archived",
      draft: "Draft",
      featured: "Featured",
      featuredPrimary: "Featured highlight",
      views: "views",
      clicks: "clicks",
      reactionsRegistered: "reactions",
      averageOverall: "overall average",
      coursesAvailable: "courses available",
      records: "records",
      availableNow: "Available now",
      inDraft: "In draft",
      prepare: "In preparation",
      waitingRelease: "waiting to be published",
    },
    preferences: {
      themeLight: "Light mode",
      themeDark: "Dark mode",
      language: "Language",
      enableEmailAlerts: "Enable email alerts",
      disableEmailAlerts: "Disable email alerts",
    },
    auth: {
      headerTagline: "Space science course platform",
      heroEyebrow: "knowledge",
      heroTitle: "Space science courses with clear reading and direct access.",
      heroDescription: "Tracks on satellites, climate, Earth observation and space weather.",
      heroTopics: ["Satellites", "Climate", "Space weather", "Earth observation"],
      heroFootnote: "Sign in to access courses, alerts and interactions.",
      loginEyebrow: "Sign in",
      loginTitle: "Access your account",
      loginDescription: "Continue where you left off.",
      forgotPasswordLink: "Forgot password",
      registerEyebrow: "Create access",
      registerTitle: "Create your account",
      registerDescription: "Register your details to enter the platform.",
      resetEyebrow: "Password recovery",
      resetTitle: "Recover your access",
      resetDescription: "Receive a code by email and set a new password.",
      resetStepEmail: "Recovery email",
      resetStepCode: "Code and new password",
      resetCodeLabel: "Received code",
      resetNewPasswordLabel: "New password",
      resetSendCodeButton: "Send code",
      resetConfirmButton: "Change password",
      resetBackToLogin: "Back",
      resetCodeSent: "If the email is registered, we will send a recovery code.",
      resetSuccess: "Password changed successfully. Sign in with your new password.",
      resetRequestError: "Could not send the code.",
      resetConfirmError: "Could not change the password.",
      nameLabel: "Full name",
      emailLabel: "Email",
      passwordLabel: "Password",
      confirmPasswordLabel: "Confirm password",
      signInButton: "Sign in",
      registerButton: "Create account and enter",
      altAccessLabel: "alternative access",
      googleSignIn: "Continue with Google",
      googleUnavailable: "Google is unavailable in this environment",
      supportTitle: "knowledge",
      supportDescription: "Access your courses, alerts and interactions in one place.",
      notificationOptIn: "I want email alerts when new courses are published.",
      noAccount: "Don`t have an account yet?",
      createAccount: "Create account",
      haveAccount: "Already have an account?",
      signInLink: "Sign in",
      invalidCredentials: "Invalid credentials. Check your email and password.",
      registerError: "Could not create your account.",
      autoSignInError: "Account created, but automatic sign-in failed.",
    },
    layout: {
      platformTagline: "Space science learning platform.",
      navCourses: "Courses",
      navAlerts: "Alerts",
      navPublications: "Publications",
      navAnalytics: "Analytics",
      notificationsAria: "Notifications",
      guestUser: "User",
      adminRole: "Editorial team",
      readerRole: "Reader",
      adminAccess: "Administrative access enabled",
      authenticatedAccount: "Authenticated account",
      emailsEnabled: "Receiving new course alerts",
      emailsDisabled: "Email alerts turned off",
      signOut: "Sign out",
    },
    dashboard: {
      heroTitle: "Space science courses.",
      heroDescription: "Browse publications on atmosphere, satellites, climate and space weather.",
      newCourse: "New course",
      spotlightNow: "Featured now",
      readCoursePage: "Open course page",
      inboxLabel: "Your inbox",
      recentAlerts: "Recent alerts",
      seeAllNotifications: "See all notifications",
      noAlertsTitle: "Your inbox is still empty",
      noAlertsDescription: "New published courses appear here.",
      liveNow: "Live now",
      publishedCourses: "Published courses",
      noPublishedTitle: "No published courses yet",
      noPublishedDescription:
        "When a new learning path goes live, it will appear here with cover, summary and direct Moodle access.",
      onlyFeaturedTitle: "The featured area above currently holds the active publication",
      onlyFeaturedDescription: "Publish more courses to expand the selection.",
    },
    notifications: {
      label: "Alerts",
      title: "Notifications",
      description: "New published courses appear here.",
      unread: "Unread",
      unreadDescription: "Items not opened yet.",
      emptyTitle: "No notifications here",
      emptyDescription: "New published courses appear here.",
      markAllRead: "Mark all as read",
      newLabel: "New",
      markRead: "Mark as read",
      markUnread: "Mark as unread",
    },
    publications: {
      label: "Publications",
      title: "Publications and drafts",
      description: "Manage title, cover, highlight and status.",
      summary: "Summary",
      publishAction: "Publish",
      newLabel: "New publication",
      newTitle: "New course",
      newDescription: "Fill in the main details, save as draft and publish when ready.",
      editDescription: "Adjust the text, images and highlight for this publication.",
    },
    analytics: {
      label: "Analytics",
      title: "Course performance",
      description: "Overview of published courses.",
      viewsHelper: "Course pages",
      clicksHelper: "Moodle visits",
      ctrHelper: "Average conversion",
      ratingHelper: "Ratings",
      impactTab: "Overall impact",
      conversionTab: "Moodle traffic",
      socialTab: "Social response",
      rankingTitle: "Overall impact ranking",
      scorePrefix: "Score",
      conversionTitle: "Moodle outbound traffic",
      socialTitle: "Social and rating engagement",
      likesHelper: "Likes",
      commentsHelper: "Comments",
      averageHelper: "Overall average",
      ctrLabel: "CTR",
    },
    course: {
      curatorLabel: "Editorial curation",
      publishedIn: "Published on",
      communityAverage: "community average",
      aboutCourse: "About the course",
      recentReviews: "Recent reviews",
      reactTitle: "React to this course",
      interestSignal: "Interest signal",
      accumulatedLikes: "total likes",
      liked: "Liked",
      like: "Like",
      yourReading: "Your reading",
      reviewPlaceholder: "Share an optional comment about your experience with this course.",
      saveReview: "Save review",
      publicComment: "Public comment",
      publicCommentDescription:
        "Use this space to leave reading impressions, recommendations or extra context for anyone still choosing a learning path.",
      commentPlaceholder: "Write your comment about the course.",
      publishComment: "Publish comment",
      reviewSaved: "Review saved successfully.",
      commentPublished: "Comment published.",
      likeError: "Could not register the like.",
      reviewError: "Could not save the review.",
      commentError: "Could not publish the comment.",
      community: "Community",
      readingsAndComments: "Readings and comments",
      noComments: "There are no published comments for this course yet.",
      continueReading: "Keep reading",
      moreCourses: "More courses",
      noRelatedCourses: "There are no related published courses yet.",
      continueInMoodle: "Continue in Moodle",
    },
    courseForm: {
      createTitle: "Course details",
      editTitle: "Edit publication",
      titleLabel: "Title",
      titlePlaceholder: "Applied space meteorology course",
      summaryLabel: "Summary",
      summaryPlaceholder: "Short summary for the course page.",
      descriptionLabel: "Full description",
      descriptionPlaceholder: "Describe context, audience, skills and motivations for the course.",
      urlLabel: "Moodle URL",
      urlPlaceholder: "https://moodle.cptec.inpe.br/...",
      imagesTitle: "Images and highlight",
      uploadLabel: "Local upload",
      uploadHint: "Upload cover and supporting images.",
      externalUrlsLabel: "External URLs",
      externalUrlsHint: "Use one URL per line.",
      featuredLabel: "Place this course in the main highlight.",
      currentImages: "Current images",
      localFilesTitle: "Local files ready",
      localFilesHint: "Local uploads stay saved in this browser until you publish or clear the draft.",
      removeFile: "Remove file",
      draftHint: "Save as draft and publish when ready.",
      autosaveReady: "Local draft active",
      autosaveSaved: "This form keeps saving automatically in this browser, even if you leave the page.",
      autosaveRestored: "Your earlier draft was restored in this browser so you can continue where you stopped.",
      lastSaved: "Last autosave",
      clearLocalDraft: "Clear local draft",
      saveDraft: "Save draft",
      saveChanges: "Save changes",
    },
  },
  es: {
    common: {
      open: "Abrir",
      course: "Curso",
      readAndAdvance: "Leer y continuar",
      likes: "me gusta",
      comments: "comentarios",
      ratingSuffix: "de nota",
      averageRating: "de nota media",
      published: "Publicado",
      archived: "Archivado",
      draft: "Borrador",
      featured: "Destacado",
      featuredPrimary: "Destacado principal",
      views: "vistas",
      clicks: "clics",
      reactionsRegistered: "reacciones",
      averageOverall: "promedio general",
      coursesAvailable: "cursos disponibles",
      records: "registros",
      availableNow: "Disponible ahora",
      inDraft: "En borrador",
      prepare: "En preparación",
      waitingRelease: "pendiente de publicación",
    },
    preferences: {
      themeLight: "Modo claro",
      themeDark: "Modo oscuro",
      language: "Idioma",
      enableEmailAlerts: "Activar alertas por correo",
      disableEmailAlerts: "Desactivar alertas por correo",
    },
    auth: {
      headerTagline: "Plataforma de cursos en ciencias espaciales",
      heroEyebrow: "knowledge",
      heroTitle: "Cursos en ciencias espaciales con lectura clara y acceso directo.",
      heroDescription: "Rutas sobre satelites, clima, observacion de la Tierra y tiempo espacial.",
      heroTopics: ["Satelites", "Clima", "Tiempo espacial", "Observacion de la Tierra"],
      heroFootnote: "Entra para acceder a cursos, alertas e interacciones.",
      loginEyebrow: "Entrar",
      loginTitle: "Accede a tu cuenta",
      loginDescription: "Continua desde donde lo dejaste.",
      forgotPasswordLink: "Olvide mi contrasena",
      registerEyebrow: "Crear acceso",
      registerTitle: "Crea tu cuenta",
      registerDescription: "Registra tus datos para entrar en la plataforma.",
      resetEyebrow: "Recuperar contrasena",
      resetTitle: "Recupera tu acceso",
      resetDescription: "Recibe un codigo por correo y define una nueva contrasena.",
      resetStepEmail: "Correo de recuperacion",
      resetStepCode: "Codigo y nueva contrasena",
      resetCodeLabel: "Codigo recibido",
      resetNewPasswordLabel: "Nueva contrasena",
      resetSendCodeButton: "Enviar codigo",
      resetConfirmButton: "Cambiar contrasena",
      resetBackToLogin: "Volver",
      resetCodeSent: "Si el correo esta registrado, enviaremos un codigo de recuperacion.",
      resetSuccess: "Contrasena alterada con exito. Entra usando la nueva contrasena.",
      resetRequestError: "No fue posible enviar el codigo.",
      resetConfirmError: "No fue posible cambiar la contrasena.",
      nameLabel: "Nombre completo",
      emailLabel: "Correo",
      passwordLabel: "Contrasena",
      confirmPasswordLabel: "Confirmar contrasena",
      signInButton: "Entrar",
      registerButton: "Crear cuenta y entrar",
      altAccessLabel: "acceso alternativo",
      googleSignIn: "Entrar con Google",
      googleUnavailable: "Google no esta disponible en este entorno",
      supportTitle: "knowledge",
      supportDescription: "Accede a tus cursos, alertas e interacciones en un solo lugar.",
      notificationOptIn: "Quiero recibir avisos por correo cuando se publiquen nuevos cursos.",
      noAccount: "Todavia no tienes cuenta?",
      createAccount: "Crear cuenta",
      haveAccount: "Ya tienes cuenta?",
      signInLink: "Iniciar sesion",
      invalidCredentials: "Credenciales invalidas. Revisa tu correo y contrasena.",
      registerError: "No fue posible crear tu cuenta.",
      autoSignInError: "La cuenta fue creada, pero no se pudo iniciar sesion automaticamente.",
    },
    layout: {
      platformTagline: "Plataforma de cursos en ciencias espaciales.",
      navCourses: "Cursos",
      navAlerts: "Alertas",
      navPublications: "Publicaciones",
      navAnalytics: "Analítica",
      notificationsAria: "Notificaciones",
      guestUser: "Usuario",
      adminRole: "Equipo editorial",
      readerRole: "Lector",
      adminAccess: "Acceso administrativo activo",
      authenticatedAccount: "Cuenta autenticada",
      emailsEnabled: "Recibiendo alertas de nuevos cursos",
      emailsDisabled: "Alertas por correo desactivadas",
      signOut: "Salir",
    },
    dashboard: {
      heroTitle: "Cursos en ciencias espaciales.",
      heroDescription: "Explora publicaciones sobre atmósfera, satélites, clima y tiempo espacial.",
      newCourse: "Nuevo curso",
      spotlightNow: "Destacado ahora",
      readCoursePage: "Abrir página del curso",
      inboxLabel: "Tu bandeja",
      recentAlerts: "Alertas recientes",
      seeAllNotifications: "Ver todas las notificaciones",
      noAlertsTitle: "Tu bandeja todavía está vacía",
      noAlertsDescription: "Los nuevos cursos publicados aparecen aquí.",
      liveNow: "En el aire",
      publishedCourses: "Cursos publicados",
      noPublishedTitle: "Aún no hay cursos publicados",
      noPublishedDescription:
        "Cuando una nueva ruta salga al aire, aparecerá aquí con portada, resumen y acceso directo a Moodle.",
      onlyFeaturedTitle: "El destaque superior concentra la publicación activa en este momento",
      onlyFeaturedDescription: "Publica más cursos para ampliar la selección.",
    },
    notifications: {
      label: "Alertas",
      title: "Notificaciones",
      description: "Los nuevos cursos publicados aparecen aquí.",
      unread: "No leídas",
      unreadDescription: "Elementos aún no abiertos.",
      emptyTitle: "No hay notificaciones aquí",
      emptyDescription: "Los nuevos cursos publicados aparecen aquí.",
      markAllRead: "Marcar todas como leídas",
      newLabel: "Nueva",
      markRead: "Marcar como leída",
      markUnread: "Marcar como no leída",
    },
    publications: {
      label: "Publicaciones",
      title: "Publicaciones y borradores",
      description: "Gestiona título, portada, destaque y estado.",
      summary: "Resumen",
      publishAction: "Publicar",
      newLabel: "Nueva publicación",
      newTitle: "Nuevo curso",
      newDescription: "Completa los datos principales, guarda como borrador y publica cuando esté listo.",
      editDescription: "Ajusta el texto, las imágenes y el destaque de esta publicación.",
    },
    analytics: {
      label: "Analítica",
      title: "Desempeño de los cursos",
      description: "Vista general de los cursos publicados.",
      viewsHelper: "Páginas del curso",
      clicksHelper: "Accesos a Moodle",
      ctrHelper: "Conversión media",
      ratingHelper: "Evaluaciones",
      impactTab: "Impacto general",
      conversionTab: "Salida a Moodle",
      socialTab: "Respuesta social",
      rankingTitle: "Ranking general de impacto",
      scorePrefix: "Puntuación",
      conversionTitle: "Tráfico de salida hacia Moodle",
      socialTitle: "Participación social y valoraciones",
      likesHelper: "Me gusta",
      commentsHelper: "Comentarios",
      averageHelper: "Promedio general",
      ctrLabel: "CTR",
    },
    course: {
      curatorLabel: "Curaduría editorial",
      publishedIn: "Publicado el",
      communityAverage: "promedio de la comunidad",
      aboutCourse: "Sobre el curso",
      recentReviews: "Evaluaciones recientes",
      reactTitle: "Reaccionar al curso",
      interestSignal: "Señal de interés",
      accumulatedLikes: "me gusta acumulados",
      liked: "Te gusta",
      like: "Me gusta",
      yourReading: "Tu lectura",
      reviewPlaceholder: "Comparte un comentario opcional sobre tu experiencia con este curso.",
      saveReview: "Guardar evaluación",
      publicComment: "Comentario público",
      publicCommentDescription:
        "Usa este espacio para registrar impresiones de lectura, recomendaciones o contexto adicional para quien aún está eligiendo la ruta.",
      commentPlaceholder: "Escribe tu comentario sobre el curso.",
      publishComment: "Publicar comentario",
      reviewSaved: "Evaluación guardada con éxito.",
      commentPublished: "Comentario publicado.",
      likeError: "No fue posible registrar el me gusta.",
      reviewError: "No fue posible guardar la evaluación.",
      commentError: "No fue posible publicar el comentario.",
      community: "Comunidad",
      readingsAndComments: "Lecturas y comentarios",
      noComments: "Todavía no hay comentarios publicados para este curso.",
      continueReading: "Seguir leyendo",
      moreCourses: "Más cursos",
      noRelatedCourses: "Todavía no existen cursos relacionados publicados.",
      continueInMoodle: "Continuar en Moodle",
    },
    courseForm: {
      createTitle: "Datos del curso",
      editTitle: "Editar publicación",
      titleLabel: "Título",
      titlePlaceholder: "Curso de meteorología espacial aplicada",
      summaryLabel: "Resumen",
      summaryPlaceholder: "Resumen corto para la página del curso.",
      descriptionLabel: "Descripción completa",
      descriptionPlaceholder: "Describe el contexto, público, habilidades y motivaciones del curso.",
      urlLabel: "URL de Moodle",
      urlPlaceholder: "https://moodle.cptec.inpe.br/...",
      imagesTitle: "Imágenes y destaque",
      uploadLabel: "Carga local",
      uploadHint: "Sube portadas e imágenes de apoyo.",
      externalUrlsLabel: "URLs externas",
      externalUrlsHint: "Usa una URL por línea.",
      featuredLabel: "Colocar este curso en el destaque principal.",
      currentImages: "Imágenes actuales",
      draftHint: "Guarda como borrador y publica cuando esté listo.",
      saveDraft: "Guardar borrador",
      saveChanges: "Guardar cambios",
    },
  },
} as const;

export type Messages = (typeof dictionaries)[Language];

export function getMessages(language: Language): Messages {
  return dictionaries[language] ?? dictionaries[DEFAULT_LANGUAGE];
}
